[tool.poetry]
name = "appui-automator"
version = "0.1.0"
description = ""
authors = ["Kelvin.Ye <testmankelvin@163.com>"]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[[tool.poetry.source]]
name = "douban"
url = "https://pypi.douban.com/simple/"
secondary = true

[tool.poetry.dependencies]
python = "^3.7"
uiautomator2 = "^2.6.1"
adbutils = "^0.7.1"
weditor = "^0.4.3"
jsonpath = "^0.82"
orjson = "^2.6.2"
pytest = "^5.4.1"
pytest-html = "^2.1.1"
pytest-dependency = "^0.5.1"
pytest-ordering = "^0.6"
pytest-sugar = "^0.9.2"
allure-pytest = "^2.8.12"
sqlalchemy = "^1.3.15"
cx-oracle = "^7.3.0"
sshtunnel = "^0.1.5"
selenium = "^3.141.0"
flake8 = "^3.8.3"
yapf = "^0.30.0"
pycryptodome = "^3.9.8"
xlwings = "^0.20.7"
pytest-rerunfailures = "^9.1"
scikit-image = "^0.17.2"
imutils = "^0.5.3"
findit = "^0.5.8"
imageio = "~=2.8.0"
imageio-ffmpeg = "~=0.4.2"
websocket_client = "~=0.57.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
